### ISSUE TITLE
Not being able to push my changes in GitHub

### ISSUE THREAD

**Issue by dasi0075** [dasi0075/responsive-recipe-book#1]
Hi @thomasjbradley 
I am having a problem pushing my changes in github for this typography assignment. I forked and cloned as usual for web dev but I may have done something wrong.
Could you help me? 

Thank you
Nadia

**Comment by thomasjbradley** [comment]
Let’s double check that you cloned the forked version.

In GitHub Desktop, in the menu go to `Repository > Repository Settings`. In the URL there do you see your username or `acgd-webdev-4` username?

**Comment by dasi0075** [comment]
Sorry @thomasjbradley I am in graphic design class, hold on let me check

**Comment by dasi0075** [comment]
<img width="966" alt="Screen Shot 2020-01-09 at 3 05 40 PM" src="https://user-images.githubusercontent.com/43067752/72100893-7898ac00-32f1-11ea-810c-090eb95ff10d.png">
 
@thomasjbradley That's how is showing acgd-webdev-4 i think

**Comment by thomasjbradley** [comment]
I don’t see the "Repository settings" window in that screenshot.

**Comment by dasi0075** [comment]
@thomasjbradley hold on sending again

**Comment by dasi0075** [comment]
<img width="443" alt="Screen Shot 2020-01-09 at 3 43 04 PM" src="https://user-images.githubusercontent.com/43067752/72103194-b6e49a00-32f6-11ea-977b-c77f8bba186f.png">
@thomasjbradley  is this the one?

**Comment by thomasjbradley** [comment]
Nope.

In GitHub Desktop, in the menu go to `Repository > Repository Settings`. What does it show in that URL?

**Comment by dasi0075** [comment]
Ok

**Comment by dasi0075** [comment]
<img width="537" alt="Screen Shot 2020-01-09 at 3 45 46 PM" src="https://user-images.githubusercontent.com/43067752/72103379-10e55f80-32f7-11ea-9dcf-653363250c80.png">

**Comment by dasi0075** [comment]
@thomasjbradley should  I change to dasi0075?

**Comment by thomasjbradley** [comment]
Yep!

**Comment by dasi0075** [comment]
@thomasjbradley Ok I did is a bit slow lets see

**Comment by dasi0075** [comment]
Oh it worked thank you Thomas!  Sorry to bother, have a nice day!
